[package]
name = "rust-tracer"
version = "0.1.0"
authors = ["Andrew Cobb <andrew.cobb@gmail.com>"]

[profile.release]
# debug = true

[dependencies]
image = "*"
num = "*"
rand = "*"
num_cpus = "*"
byteorder = "*"